spring.application.name=Train


spring.datasource.url = jdbc:mysql://localhost:3306/train
spring.datasource.username = root
spring.datasource.password = Ish@n781

#JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
