spring.application.name=Train
server.port=${PORT:8080}


spring.datasource.url = ${DB_URL:jdbc:mysql://localhost:3306/train}
spring.datasource.username = ${DB_USERNAME:root}
spring.datasource.password = ${DB_PASSWORD:Ish@n781}

#JPA
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
